service: secure-password-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    TABLE_NAME: secure-secrets
    ENCRYPTION_KEY: "_nQF7e7aQoiHjpBMYg99Gwm5_6dpfwnt7_BL4Y7c2Og="
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource: arn:aws:dynamodb:us-east-1:*:table/secure-secrets

functions:
  createPwd:
    handler: handler.create_pwd
    events:
      - httpApi:
          path: /pwd
          method: post
  getPwd:
    handler: handler.get_pwd
    events:
      - httpApi:
          path: /pwd/{pwdId}
          method: get
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux